### ISSUE TITLE
Improve route command (Jump Bridges) 

### ISSUE THREAD

**Issue by ThirteenFish** [Hijacker/vmbot#35]
- hold for now, route pending removal

It's 2015, all the cool kids use github issues instead of TODO files

**Comment by ThirteenFish** [comment]
What exactly were the problems with route and can they be fixed by sending a pm?

**Comment by Hijacker** [comment]
Text chat is just a terrible interface for eve route planning. It lacks a map which is always very helpful, it is awkward to use advanced features like avoiding systems / regions, finding and keeping an alternative for one system, it lacks jump bridge integration. IMHO it doesn't need to be replicated; dotlan and gts exist and are doing a superb job at it.

**Comment by ThirteenFish** [comment]
So it sounds like we should remove route entirely then.

**Comment by Hijacker** [comment]
Yase.
