### ISSUE TITLE
Invisible unicode character is not always invisible

### ISSUE THREAD

**Issue by ThirteenFish** [Hijacker/vmbot#38]
This is an issue entirely because because pimp is using a terrible jabber client, but he has complained more than once now.

(03:08:08 PM) kamden_line: pimpsay PIMP_Road
(03:08:08 PM) Morgooglie: ​PIMP_Road i want a bucket full of money covered rainbows
(03:08:27 PM) PIMP_Road: Sun
(03:09:14 PM) PIMP_Road: We need to fix the &#8203 thing
(03:09:16 PM) kamden_line: praise it everyday
(03:10:16 PM) PIMP_Road: <Morgooglie> &#8203;PIMP_Road i want a bucket full of money covered rainbows
(03:10:34 PM) PIMP_Road: ^ fix that please code warriors
(03:11:37 PM) thirteen_fish: fix your jabber client
(03:11:39 PM) kamden_line: (3:08:07 PM) Morgooglie: ​PIMP_Road i want a bucket full of money covered rainbows
(03:11:43 PM) kamden_line: i think its just you nerd
(03:12:04 PM) kamden_line: wait
(03:12:07 PM) kamden_line: are you using jappix?
(03:12:14 PM) PIMP_Road: Talkonaught
(03:12:19 PM) kamden_line: there's your problem
(03:12:19 PM) PIMP_Road: On iphone
(03:12:52 PM) PIMP_Road: I demand cross platform operation from the crack coders

So the easiest way to do this is to [stop the bot from responding to itself](https://github.com/Hijacker/vmbot/blob/master/vmbot.py#L321). I had hoped that leaving it on would lead to ~emergent behaviour~ but it's almost always detrimental. That said, there are a few commands where it is not detrimental: the z0r and lion chains, pickone, and chasesay. That hints that there is a better way of doing this than a total ban, possibly as an option to `@botcmd`. Given that we already want to modify `@botcmd` for pm replies, this might not be too much more work.

**Comment by Hijacker** [comment]
Personally I don't think the replies to itself provide much extra entertainment. As far as I'm concerned, turning it off would be totally fine.

**Comment by TheJokr** [comment]
If pimp's client can't parse HTML entities, it won't be able to parse enhancements from #36 either (read: pimp should get a proper jabber client).
