### ISSUE TITLE
Bot continues to respond to itself

### ISSUE THREAD

**Issue by TheJokr** [Hijacker/vmbot#45]
Even though `acceptownmsgs=True` was removed in e7a472f61412b71182ae3499a755fa1c75c821fd, the bot still responds to itself.
The fix for #38 introduced this behaviour.

Also, all the [chains](https://github.com/Hijacker/vmbot/blob/058d74c6ac325043c4fc207652c4c07499ec47dd/fun.py#L124) won't work if the bot doesnt respond to it's own commands. Might as well remove them.

**Comment by Hijacker** [comment]
The bot responding to its own chains is a side effect and not planned behavior, so the chains are fine.

**Comment by ThirteenFish** [comment]
Mostly fixed in 60fbed0ac1eca8b26a81990ed1e50a6e5e8ef65b
